### ISSUE TITLE
Give team membership info

### ISSUE THREAD

**Issue by parkr** [benbalter/squad_goals#2]
Hi @benbalter! This is super cool. [Got it all setup for Jekyll now](https://teams.jekyllrb.com/).

It'd be cool for users to see some (cached?) membership info, whether it's the team listed or just a count, like:

> Join 11 other Jekyllers on the Build team

It could foster a sense of community, like you're not the only one?

**Comment by benbalter** [comment]
Queueing this up as an open source Friday project for tomorrow.
